### ISSUE TITLE
Fetch API cannot load URL scheme "file" is not supported.

### ISSUE THREAD

**Issue by aquaServiceTest** [aaronksaunders/firebaseStorage2#1]
Hi, I tried to use your code into mine project, altough, when running on real android device, the method makeFileIntoBlob() fails because of the following error: "Fetch API cannot load file:///storage/emulated/0/Android/data/..../cache/1471709140577.png. URL scheme "file" is not supported."

Would this be an error because of permissions or something?
## 

Also when loading my app in a browser, Chrome works fine but when i'm trying Firefox, am getting error with CORS-header 'Access-Control-Allow-Origin' is missing

**Comment by aaronksaunders** [comment]
my bad... I missed this in my testing, got confused between the two versions of the app. The fix is as follows.

1) install the File plugin - cordova plugin add cordova-plugin-file
2) add the code below to`makeFileIntoBlob`
3) see source for complete set of changes

```
   makeFileIntoBlob(_imagePath) {

    // INSTALL PLUGIN - cordova plugin add cordova-plugin-file
    if (this.platform.is('android')) {
      return new Promise((resolve, reject) => {
        window.resolveLocalFileSystemURL(_imagePath, (fileEntry) => {

          fileEntry.file((resFile) => {

            var reader = new FileReader();
            reader.onloadend = (evt: any) => {
              var imgBlob: any = new Blob([evt.target.result], { type: 'image/jpeg' });
              imgBlob.name = 'sample.jpg';
              resolve(imgBlob);
            };

            reader.onerror = (e) => {
              console.log('Failed file read: ' + e.toString());
              reject(e);
            };

            reader.readAsArrayBuffer(resFile);
          });
        });
      });
    } else {
      return fetch(_imagePath).then((_response) => {
        return _response.blob();
      }).then((_blob) => {
        return _blob;
      }).catch((_error) => {
        alert(JSON.stringify(_error.message));
      });
    }
  }
```

**Comment by aquaServiceTest** [comment]
Thank you very much, it works! One last thing, what changes do I have to do to making it work in ios devices?

**Comment by aaronksaunders** [comment]
there are no issues on ios...

**Comment by aquaServiceTest** [comment]
Yes, I think there was something wrong in the build with Visual Studio. Thank you very much, it works perfectly

**Comment by saurabhvyas** [comment]
Hi aaron I was wondering why we have to write this extra code just for android,Isnt file api supported on android devices?Also what is the difference between code in this repo and the one with firebase3 in which you uploaded an image?

**Comment by aaronksaunders** [comment]
@saurabhvyas i thought the polyfill for fetch would work for android and it doesnt... the reality is that it is easier to just use the File base solution for both IOS & Android

**Comment by JackMj** [comment]
hey Aaron im experiencing some issues with fetch im getting this error 'Cannot find name 'fetch' even after installing typings install --global --save dt~whatwg-fetch

**Comment by aaronksaunders** [comment]
fetch is a polyfill.. i believe I have another example where i have replaced fetch with FileReader - https://github.com/aaronksaunders/firebaseStorage2/issues/1#issuecomment-241298220

**Comment by JackMj** [comment]
Can you please send me a link to that example

**Comment by aaronksaunders** [comment]
see the link in the comment above... i dont know where specific example is at this point, but the code snippet specified above should solve your problem.

**Comment by JackMj** [comment]
the issue still persist with fetch underlined "error cannot find name fetch"

**Comment by aaronksaunders** [comment]
see - https://github.com/aaronksaunders/ionic2firebase3/blob/master/app/pages/home/home.ts#L124

**Comment by aaronksaunders** [comment]
fixed issue, updated to latest ionic version
