### ISSUE TITLE
app hangs after entering makeFileIntoBlob function

### ISSUE THREAD

**Issue by j-West** [aaronksaunders/firebaseStorage2#3]
After cloning the repo and running it in the ionic view app, the app hangs when it enters the makeFileIntoBlob function.  The 'got image path' alert fires, but nothing returns from the blob function.

**Comment by aaronksaunders** [comment]
Log info would be helpful here; maybe you can run it in the browser and include the console long here?

**Comment by j-West** [comment]
user error, sorry
