### ISSUE TITLE
Alert on start App.

### ISSUE THREAD

**Issue by xnosx** [aaronksaunders/firebaseStorage2#4]
Hello Aaron,

When I start the App give me an Alert with the following mensage:

> The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.

I have enabled the anonymous authentication in the Firebase Authentication / Sign in Method project and rebuild the App, but the problem persist, can you check if you have the same problem ?, I already set the apiKey, authDomain and another params on firebase.config .ts.

Thanks a lot!

**Comment by aaronksaunders** [comment]
my bad, need to update the readme... I have hardcoded a user in this example.
See https://github.com/aaronksaunders/firebaseStorage2/blob/master/src/pages/home/home.ts#L36

```javascript
firebase.auth().signInWithEmailAndPassword('newuser@mail.com', 'password')
```

so you would need to either add your own user, using email auth, or create a user matching these credentials.

@xnosx

**Comment by xnosx** [comment]
Excelent @aaronksaunders the error is gone! but!

I have now to errors taking a pic, the errors are:

> Alert: got image path file:///storage/emulated/0/Android/data/com.ionicframework.firebasestorage2567091/cache/1487838596231.jpg

And then

> Alert: Error window.resolveLocalFileSystemURL is not a function

I´ll take a look to the code, but if this sounds familiar tell me something!

Thanks and BR!

**Comment by aaronksaunders** [comment]
need to run `ionic state restore` to make sure that you have all of the plugins installed... look in `package.json` you will see what plugins are required

**Comment by xnosx** [comment]
Thanks, is working fine now!

Have another Alerts, before and after upload files, etc... but I´ll take a look to the code to try fix it.

Thanks again for your time!

BR @aaronksaunders
